title = "blog.nabeliwo.me"
baseurl = "http://blog.nabeliwo.me/"

[permalinks]
post = "/:year/:month/:slug/"

paginate = 10
paginatePath = "page"

# More options
[params]
author = "nabeliwo"
description = "blog.nabeliwo.meは@nabeliwoの技術だったりポエムだったりのブログです。三角が好きです。"
socialbase = "nabeliwo"
facebook = "hirokiwatanabe19"
