title = "nabeliwonote"
baseurl = "https://blog.nabeliwo.me/"
paginate = 10
paginatePath = "page"
enableEmoji = true

[permalinks]
  post = "/:year/:month/:slug/"

# More options
[params]
  author = "nabeliwo"
  description = "nabeliwonoteは@nabeliwoによる技術系ポエムです。"
  socialbase = "nabeliwo"
  facebook = "hirokiwatanabe19"
